language: java
deploy:
  provider: heroku
  api_key:
    secure: aerhKa8CiQhFkPMZ7s8EX8VrXl3GYzVaCoYMCXTN0WG6Bdurrz+TX18jXPKZqVOtJV8yFicLqfLXqZChvfY/o1Cg8bHEfupuBoJ/IUcYY+SloO2XnxhYfEfYUi2Idq0qgjXr97Fhj/jdIqoDFSuYFWZzITPGgS8aBOosctzElZRnqS54DOrtMz5hTbL8P8aW6QaSm0kJcI0j5DT20XlBmFjBrNAEUJrYhgmqK3qnXwF00WHGRPA4inFGOTRjQEy8Q/yNPMoz8y/zBwwF9WqO2jB+To6hMe5SnG/CmKZBTrNVWfccI3dVn3RWCzQK4epu1Dg5mk4VYhS1tqgsHXuoNi0XkwWQcO6Fv32x6SKsPfzrVh+hawUuq4MRF1F0F8TH1LLktv6AEqqUouORrc2T1LAcSZMJh56L/eOSEJVe58ymtUguCWr6QcXOIgYQbwNA0JqwEMk5XZBP6WPRKZW11XcFucbx/hMFl2FqpAMfQlSopgBwha8I5NS4s0lMn5JKewdIjv+2fKWlaNGBzozjt81FbI+0kHXuz4Fz20HpIV3lwO4l5OFTf26PRJTV4ZnqqbS8DtCekKS8HZOlaw1vzX7ZG0KhMEafnGXJ+WoHOQUg3wXrzukOMcNydz0o9h99aNyYrnPmrg0LW3v2bgLzRFkYGMn0uEARue0ovZ0FeLs

